### ISSUE TITLE
PLUGIN CRASH

### ISSUE THREAD

**Issue by etunni** [HugoJourdan/Glyphs-Script#2]
The Plugin Context Manager.glyphsPlugin has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

  File "GlyphsApp/GlyphsApp/plugins.py", line 845, in loadPlugin

  File "plugin.py", line 36, in settings
    os.chdir(os.path.dirname(self.jsonPath))

FileNotFoundError: [Errno 2] No such file or directory: '~/Library/Application Support/Glyphs 3/info'

App:3.1.1-3141 Plugin:1.0-1.0

**Comment by HugoJourdan** [comment]
Thanks for your report.
Fixed.

**Comment by etunni** [comment]
No crash at loading. :)
But don't used yet.
